FROM node:alpine

RUN npm config set strict-ssl false
RUN npm config set proxy http://epsvc%5Cweiw:!Shanghai1@proxy.police.edmonton.ab.ca:8080
RUN npm config set https.proxy http://epsvc%5Cweiw:!Shanghai1@proxy.police.edmonton.ab.ca:8080

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
CMD npm start